// Constantes da aplicação

export const ESPECIALIDADES_MEDICAS = [
  "CIRURGIA CABECA E PESCOCO",
  "CIRURGIA GERAL", 
  "CIRURGIA TORACICA",
  "CIRURGIA VASCULAR",
  "CLINICA GERAL",
  "HEMATOLOGIA",
  "INTENSIVISTA",
  "NEFROLOGIA",
  "NEUROCIRURGIA",
  "NEUROLOGIA",
  "ODONTOLOGIA C.TRAUM.B.M.F.",
  "ONCOLOGIA CIRURGICA",
  "ONCOLOGIA CLINICA/CANCEROLOGIA",
  "ORTOPEDIA/TRAUMATOLOGIA",
  "PROCTOLOGIA",
  "UROLOGIA",
  "BUCOMAXILO",
  "HEPATOLOGISTA",
  "MASTOLOGIA",
  "RESIDENTE"
];

export const ORIGENS_RESERVA = ["SISREG", "ONCOLOGIA"];

export const STATUS_RESERVA = ["Ativa", "Cancelada", "Internado"];

export const ESPECIALIDADES_ONCOLOGIA = ["HEMATOLOGIA", "ONCOLOGIA"];